name: CMake

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install libsdl2-dev libsdl2-image-dev
    
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build

  win32:
    runs-on: windows-latest
    
    env:
      SDL_VERSION: 2.28.5
      SDL_IMAGE_VERSION: 2.8.2
    
    steps:
    - uses: actions/checkout@v3

    - name: Download SDL
      run: |
        Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/release-$env:SDL_VERSION/SDL2-devel-$env:SDL_VERSION-VC.zip" -OutFile C:\SDL.zip
        Invoke-WebRequest "https://github.com/libsdl-org/SDL_image/releases/download/release-$env:SDL_IMAGE_VERSION/SDL2_image-devel-$env:SDL_IMAGE_VERSION-VC.zip" -OutFile C:\SDL_image.zip
        Expand-Archive C:\SDL.zip -DestinationPath C:\
        Expand-Archive C:\SDL_image.zip -DestinationPath C:\

    - name: Configure
      run: cmake -A Win32 -B build -DCMAKE_PREFIX_PATH="C:/SDL2-$env:SDL_VERSION/cmake;C:/SDL2_image-$env:SDL_IMAGE_VERSION/cmake"
  
    - name: Build
      run: cmake --build build --config Release

    - name: Install
      run: cmake --install build --prefix install

    - uses: actions/upload-artifact@v3
      with:
        name: libsecam-win32-${{ github.sha }}
        path: install
